In [1]:
print("Merhaba! Bibliometric Normalization System başladı.")

Merhaba! Bibliometric Normalization System başladı.

In [3]:
import pandas as pd

print(pd.__version__)

2.2.2

In [13]:
import pandas as pd

In [17]:
df = pd.read_excel("input/combining yazar listesi.xlsx")

In [19]:
df.head()

,Unnamed: 0,Author Full Name,Title,Publication Name / Source,Publication Year,Times Cited,Abstract,Author Keywords,Author Address / Affiliation,Author
0,1,"Hertz, Frederik Boetius",Vaginal microbiome following orally administer...,APMIS,2022,10,"Here, we present a longitudinal shotgun sequen...",Vaginal microbiome; healthy microbiome; women;...,"[Hertz, Frederik Boetius; Bjornsdottir, Maria ...","Hertz, Frederik Boetius"
1,2,"Garmendia, Jenny Valentina",Microbiota and Recurrent Pregnancy Loss (RPL);...,MICROORGANISMS,2024,25,Recurrent Pregnancy Loss (RPL) affects 1-2% of...,recurrent pregnancy loss (RPL); recurrent impl...,"[Garmendia, Jenny Valentina; De Sanctis, Claud...","Garmendia, Jenny Valentina"
2,3,"Saraf, Viqar Sayeed",Vaginal microbiome: normalcy vs dysbiosis,ARCHIVES OF MICROBIOLOGY,2021,145,It has been long understood that the vaginal m...,Vaginal microbiome; Vaginal dysbiosis; Bacteri...,"[Saraf, Viqar Sayeed; Sheikh, Sohail Aslam; Ah...","Saraf, Viqar Sayeed"
3,4,"Kim, Juewon",Systems-level restoration of vaginal and gut m...,ISME JOURNAL,2026,0,"Bacterial vaginosis (BV), often driven by Gard...",vaginal dysbiosis; gut-vagina axis; Lactobacil...,"[Kim, Juewon; Kim, Woo-il] Konkuk Univ, Coll M...","Kim, Juewon"
4,5,"Yang, Siwen",Effect of Oral Probiotic Lactobacillus rhamnos...,NUTRIENTS,2020,75,Spontaneous preterm birth is associated with v...,probiotics; pregnancy; bacterial vaginosis; mi...,"[Yang, Siwen; Challis, John R. G.; Bocking, Al...","Yang, Siwen"

In [21]:
df.shape

(12198, 10)

In [23]:
df.columns

Index(['Unnamed: 0', 'Author Full Name', 'Title', 'Publication Name / Source',
       'Publication Year', 'Times Cited', 'Abstract', 'Author Keywords',
       'Author Address / Affiliation', 'Author'],
      dtype='object')

In [25]:
for col in df.columns:
    print(col)

Unnamed: 0
Author Full Name
Title
Publication Name / Source
Publication Year
Times Cited
Abstract
Author Keywords
Author Address / Affiliation
Author

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12198 entries, 0 to 12197
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    12198 non-null  object
 1   Author Full Name              12172 non-null  object
 2   Title                         12172 non-null  object
 3   Publication Name / Source     12170 non-null  object
 4   Publication Year              12171 non-null  object
 5   Times Cited                   12171 non-null  object
 6   Abstract                      12151 non-null  object
 7   Author Keywords               10364 non-null  object
 8   Author Address / Affiliation  12162 non-null  object
 9   Author                        12169 non-null  object
dtypes: object(10)
memory usage: 953.1+ KB

In [29]:
df.isnull().sum()

Unnamed: 0                         0
Author Full Name                  26
Title                             26
Publication Name / Source         28
Publication Year                  27
Times Cited                       27
Abstract                          47
Author Keywords                 1834
Author Address / Affiliation      36
Author                            29
dtype: int64

In [31]:
df.describe(include="all")

,Unnamed: 0,Author Full Name,Title,Publication Name / Source,Publication Year,Times Cited,Abstract,Author Keywords,Author Address / Affiliation,Author
count,12198,12172,12172,12170,12171,12171,12151,10364,12162,12169
unique,12198,10383,12161,1793,26,463,12059,10350,12082,10381
top,1,"Lugli, Gabriele Andrea",A Capillary Electrophoresis Method for Analyzi...,FRONTIERS IN MICROBIOLOGY,2025,0,Background,thyroid nodules; Lactobacillus acidophilus bac...,"[Borrego-Ruiz, Alejandro] Univ Nacl Educ Dista...","Lugli, Gabriele Andrea"
freq,1,16,2,562,1767,1113,34,2,4,16

In [33]:
df.shape

(12198, 10)

In [35]:
df.columns

Index(['Unnamed: 0', 'Author Full Name', 'Title', 'Publication Name / Source',
       'Publication Year', 'Times Cited', 'Abstract', 'Author Keywords',
       'Author Address / Affiliation', 'Author'],
      dtype='object')

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12198 entries, 0 to 12197
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    12198 non-null  object
 1   Author Full Name              12172 non-null  object
 2   Title                         12172 non-null  object
 3   Publication Name / Source     12170 non-null  object
 4   Publication Year              12171 non-null  object
 5   Times Cited                   12171 non-null  object
 6   Abstract                      12151 non-null  object
 7   Author Keywords               10364 non-null  object
 8   Author Address / Affiliation  12162 non-null  object
 9   Author                        12169 non-null  object
dtypes: object(10)
memory usage: 953.1+ KB

In [39]:
df = df.drop(columns=["Unnamed: 0"])

In [41]:
df.head()

,Author Full Name,Title,Publication Name / Source,Publication Year,Times Cited,Abstract,Author Keywords,Author Address / Affiliation,Author
0,"Hertz, Frederik Boetius",Vaginal microbiome following orally administer...,APMIS,2022,10,"Here, we present a longitudinal shotgun sequen...",Vaginal microbiome; healthy microbiome; women;...,"[Hertz, Frederik Boetius; Bjornsdottir, Maria ...","Hertz, Frederik Boetius"
1,"Garmendia, Jenny Valentina",Microbiota and Recurrent Pregnancy Loss (RPL);...,MICROORGANISMS,2024,25,Recurrent Pregnancy Loss (RPL) affects 1-2% of...,recurrent pregnancy loss (RPL); recurrent impl...,"[Garmendia, Jenny Valentina; De Sanctis, Claud...","Garmendia, Jenny Valentina"
2,"Saraf, Viqar Sayeed",Vaginal microbiome: normalcy vs dysbiosis,ARCHIVES OF MICROBIOLOGY,2021,145,It has been long understood that the vaginal m...,Vaginal microbiome; Vaginal dysbiosis; Bacteri...,"[Saraf, Viqar Sayeed; Sheikh, Sohail Aslam; Ah...","Saraf, Viqar Sayeed"
3,"Kim, Juewon",Systems-level restoration of vaginal and gut m...,ISME JOURNAL,2026,0,"Bacterial vaginosis (BV), often driven by Gard...",vaginal dysbiosis; gut-vagina axis; Lactobacil...,"[Kim, Juewon; Kim, Woo-il] Konkuk Univ, Coll M...","Kim, Juewon"
4,"Yang, Siwen",Effect of Oral Probiotic Lactobacillus rhamnos...,NUTRIENTS,2020,75,Spontaneous preterm birth is associated with v...,probiotics; pregnancy; bacterial vaginosis; mi...,"[Yang, Siwen; Challis, John R. G.; Bocking, Al...","Yang, Siwen"

In [43]:
df.columns = [
    "author_full_name",
    "title",
    "journal",
    "year",
    "times_cited",
    "abstract",
    "keywords",
    "affiliation",
    "author"
]

In [45]:
df.columns

Index(['author_full_name', 'title', 'journal', 'year', 'times_cited',
       'abstract', 'keywords', 'affiliation', 'author'],
      dtype='object')

In [47]:
df["year"] = pd.to_numeric(df["year"], errors="coerce")
df["times_cited"] = pd.to_numeric(df["times_cited"], errors="coerce")

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12198 entries, 0 to 12197
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   author_full_name  12172 non-null  object
 1   title             12172 non-null  object
 2   journal           12170 non-null  object
 3   year              12169 non-null  float64
 4   times_cited       12169 non-null  float64
 5   abstract          12151 non-null  object
 6   keywords          10364 non-null  object
 7   affiliation       12162 non-null  object
 8   author            12169 non-null  object
dtypes: float64(2), object(7)
memory usage: 857.8+ KB

In [51]:
df.isnull().sum()

author_full_name      26
title                 26
journal               28
year                  29
times_cited           29
abstract              47
keywords            1834
affiliation           36
author                29
dtype: int64

In [53]:
def clean_text(text):
    """
    Metin temizleme fonksiyonu
    """

    if pd.isna(text):
        return ""

    text = str(text)

    text = text.strip()

    return text

In [55]:
clean_text("   University of Parma   ")

'University of Parma'

In [57]:
clean_text(None)

''

In [59]:
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = df[col].apply(clean_text)

In [61]:
df["author_full_name"].head(20)

0        Hertz, Frederik Boetius
1     Garmendia, Jenny Valentina
2            Saraf, Viqar Sayeed
3                    Kim, Juewon
4                    Yang, Siwen
5                  Oerlemans, E.
6                        Xu, Pei
7                     Husain, S.
8              Jepsen, Ida E. E.
9                    Yeruva, Taj
10                     Asadi, A.
11              Pino, Alessandra
12                     Cheng, Di
13           Cocomazzi, Giovanna
14       Martoni, Christopher J.
15                    Quan, Keyu
16                    Lin, Li-Te
17                     Er, Sevda
18                  Li, Congcong
19                 Chen, Tingtao
Name: author_full_name, dtype: object

In [63]:
df["author_full_name"].nunique()

10384

In [65]:
import re
import pandas as pd

def normalize_author(name):
    """
    Yazar ismini standartlaştırır.
    """

    if pd.isna(name):
        return ""

    name = str(name)

    # Baştaki ve sondaki boşlukları sil
    name = name.strip()

    # Birden fazla boşluğu teke indir
    name = re.sub(r"\s+", " ", name)

    # Büyük harfleri normale çevir
    name = name.title()

    return name

In [67]:
normalize_author("  LUGLI,   GABRIELE ANDREA ")

'Lugli, Gabriele Andrea'

In [69]:
normalize_author("chen   yang")

'Chen Yang'

In [71]:
df["normalized_author"] = df["author_full_name"].apply(normalize_author)

In [73]:
df[["author_full_name","normalized_author"]].head(20)

              author_full_name           normalized_author
0      Hertz, Frederik Boetius     Hertz, Frederik Boetius
1   Garmendia, Jenny Valentina  Garmendia, Jenny Valentina
2          Saraf, Viqar Sayeed         Saraf, Viqar Sayeed
3                  Kim, Juewon                 Kim, Juewon
4                  Yang, Siwen                 Yang, Siwen
5                Oerlemans, E.               Oerlemans, E.
6                      Xu, Pei                     Xu, Pei
7                   Husain, S.                  Husain, S.
8            Jepsen, Ida E. E.           Jepsen, Ida E. E.
9                  Yeruva, Taj                 Yeruva, Taj
10                   Asadi, A.                   Asadi, A.
11            Pino, Alessandra            Pino, Alessandra
12                   Cheng, Di                   Cheng, Di
13         Cocomazzi, Giovanna         Cocomazzi, Giovanna
14     Martoni, Christopher J.     Martoni, Christopher J.
15                  Quan, Keyu                  Quan, Keyu
16                  Lin, Li-Te                  Lin, Li-Te
17                   Er, Sevda                   Er, Sevda
18                Li, Congcong                Li, Congcong
19               Chen, Tingtao               Chen, Tingtao

In [75]:
(df["author_full_name"] != df["normalized_author"]).sum()

251

In [77]:
df["normalized_author"].value_counts().head(20)

normalized_author
                          26
Lugli, Gabriele Andrea    16
Reid, Gregor              12
Duranti, Sabrina          10
Chen, Yang                10
Turroni, Francesca         9
Yang, Bo                   9
Milani, Christian          9
Wang, Yue                  8
Alessandri, Giulia         7
Li, Jing                   7
Panpetch, Wimonrat         7
Vitetta, Luis              7
Engevik, Melinda A.        7
Duysburgh, Cindy           7
Tian, Peijun               6
Mehta, Supriya D.          6
Happel, Anna-Ursula        6
Zhang, Ting                6
Ding, Mengfan              6
Name: count, dtype: int64